Revert "adb: add transport benchmark."
This reverts commit 4cdf41957c80de7e034d127ea6127e65284ea678.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293